spring:
  application:
    name: "food-service"
  datasource:
    url: jdbc:mysql://localhost:3306/fooddb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: "{cipher}3be4fb335afb7b218a98fb499102365493d327bb73e2099169dea2a4b43325b8"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# eureka Configurations
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
